# Generated by Django 2.2.1 on 2019-06-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_newtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.CharField(default=200, max_length=5),
            preserve_default=False,
        ),
    ]
